### ISSUE TITLE
The 'check-manifest' pre-commit hook is very slow

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab#169]
Running this pre-commit hook sometimes takes more than two minutes (see log below) – significantly slowing down my development workflow – and its benefit is not entirely clear to me. @chrisjsewell Since you originally introduced this hook, could you briefly comment what we use it for in this project and whether we could maybe limit it to run when only certain files are changed, such as `setup.cfg`?

```console
% pre-commit run -v check-manifest
check-manifest...........................................................Passed
- hook id: check-manifest
- duration: 129.4s

lists of files in version control and sdist match
```

**Comment by chrisjsewell** [comment]
https://github.com/mgedmin/check-manifest/issues/141

**Comment by csadorf** [comment]
As a temporary remedy, I've set the `$SKIP` environment variable in my dev environment: `export SKIP=check-manifest`

**Comment by chrisjsewell** [comment]
@csadorf, I would just try adding as it suggests:

```yaml
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.46"
    hooks:
    - id: check-manifest
      args: [--no-build-isolation]
      additional_dependencies: [setuptools>=46.4.0]
```
